### ISSUE TITLE
Javascript Nullish coalescing operator (??) not supported

### ISSUE THREAD

**Issue by rsepierre** [olback/es6-css-minify#157] opened 2023-01-13 17:45 UTC
**Describe the bug**

**To Reproduce**
1. Use Nullish coalescing operator "??" ( https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing )
2. try to minify javacript file

**Expected behavior**
Should be able to minify file

**Screenshots**
```
[function.js]:
	[Errors]: 1
		- Unexpected token: operator (?)
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by olback** [comment] 2023-01-13 17:53
Duplicate of https://github.com/olback/es6-css-minify/issues/119

**Closed as completed** 2023-01-13 17:53 UTC
