### ISSUE TITLE
Visibility of the Minify button is unpredictable

### ISSUE THREAD

**Issue by CubeRanch** [olback/es6-css-minify#78] opened 2019-08-13 21:32 UTC
**Describe the bug**
When moving to an existing editor that contains an unsupported file type (like .php) the Minify button does not necessarily hide. Sometimes it will, usually by the second file if it does, sometimes it won't at all.

If it does hide, when moving back to a supported file type (like unminified .css) the Minify button will not necessarily show.

In all cases the Minify functionality is still available via the command palette.

**To Reproduce**
1. Navigate across the open editor tabs to an editor that contains an unsupported file type, or back to an editor that contains a supported file type.
2. The Minify button may still be visible in the status bar when on an unsupported file type, or may not be visible when on a supported file type.

**Expected behavior**
The Minify button should hide on unsupported file types and show on supported file types.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1809

**Comment by olback** [comment] 2019-08-13 22:53
The default behavior was changed to auto in the `3.0.0` release. Seems like it's not working as good as intended. The behavior can be changed by setting `es6-css-minify.hideButton` to `false`.

I'll change the default back to what it was in `2.*`.

**Comment by olback** [comment] 2019-08-13 23:59
Fixed in `3.0.2`

**Comment by tomgallagher** [comment] 2019-08-14 20:45
My minify button recently disappeared - I found I needed to change my setting from the default that I had on install

**Comment by semerda** [comment] 2019-08-20 18:36
Same here. Minify button gone. Not minifying.
Had to add     "es6-css-minify.hideButton": false
to settings.json to get the button back and now when I press it minifies.

The VSC Marketplace readme still says that save is DISABLED by default and no indication how to enable or disable the Minify button. I found the how to here inside the issues tracker.

**Comment by CubeRanch** [comment] 2019-08-20 22:54
> 
> 
> Same here. Minify button gone. Not minifying.
> Had to add "es6-css-minify.hideButton": false
> to settings.json to get the button back and now when I press it minifies.
> 
> The VSC Marketplace readme still says that save is DISABLED by default and no indication how to enable or disable the Minify button. I found the how to here inside the issues tracker.

I have a setting in my VSC settings called "Es6-CSS-minify Hide Button" with three choices: "always", "never" and "auto". After installing the latest version my button was gone as well. I had to change the setting from the default "always" to "never" or "auto". As it notes, "auto" isn't 100% reliable.

**Comment by olback** [comment] 2019-08-21 13:03
Investigating...

**Closed as completed** 2019-09-10 11:03 UTC
Labels: bug
