### ISSUE TITLE
Cant minify js files with logical nullish assignment (??=)

### ISSUE THREAD

**Issue by BVazquezAlvarez** [olback/es6-css-minify#144] opened 2022-05-05 08:22 UTC
**Describe the bug**
When a Javascript file contains a logical nullish assignment (??=) inside the minifier throws an error

**To Reproduce**
1. Go to a Javascript file
2. Insert a logical nullish assignment in that file
3. Try no minify it
4.  Throws error 	
                "[Errors]: 1
		- Unexpected token: operator (?)"

**Desktop:**
 - OS:  Windows
 - Version 10
 - Minifier version: 3.3.3

**Comment by olback** [comment] 2022-05-07 13:17
Duplicate of #119

**Closed as completed by olback** 2022-05-07 13:17 UTC
